# Settings
live_config_reload = true

# Current desktop theme
import = [ "~/.config/alacritty/themes/tokyo.toml" ]

[window]
padding = { x = 0, y = 0 }
dynamic_padding = true
opacity = 1

[shell]
program = "/bin/zsh"
args = ["-l","-c", "tmux attach || tmux"]

[font]
normal = {family = "FiraCode Nerd Font", style = "Regular"}
