[window]
padding = { x = 14, y = 3 }
dynamic_padding = false
opacity = 0.7
decorations = "None"
startup_mode = "Maximized"

[terminal.shell]
program = "/bin/zsh"
args = ["-l","-c", "tmux attach || tmux"]

[font]
normal = {family = "FiraCode Nerd Font", style = "Regular"}
size = 14

[general]
live_config_reload = true
import = [ "~/.config/alacritty/themes/kanagawa.toml" ]

[mouse]
hide_when_typing = true
