# Settings
live_config_reload = true

# Current desktop theme
import = [ "~/.config/alacritty/themes/tokyo.toml" ]

[window]
decorations = "None"
padding = { x = 0, y = 0 }
dynamic_padding = true

[shell]
program = "/bin/zsh"
args = ["-l","-c", "tmux attach || tmux"]
